use Config;
print $Config{archname}, "\n";
print $Config{osname}, "\n";
print $Config{byteorder}, "\n";
print $Config{dlext}, "\n";
print $Config{exe_ext}, "\n";
print $Config{useithreads}, "\n";
print $Config{use64bitint}, "\n";
print $Config{intsize}, "\n";
print $Config{ptrsize}, "\n";
print $Config{nvsize}, "\n";
print exists $Config{cc}, " ", exists $Config{osvers}, "\n";
print $Config::Config{perlpath}, "\n";
my $sum = 0;
$sum += $Config{SEEK_SET} if exists $Config{SEEK_SET};
print "sig_name_len: ", length($Config{sig_name}) > 10 ? 1 : 0, "\n";
my @k = sort grep { /^(archname|cc|version|osname)$/ } keys %Config;
print "keys: @k\n";
print Config::myconfig() =~ /^Summary of my perl5 \(revision 5 version/ ? 1 : 0, "\n";
print length(Config::config_sh()) > 1000 ? 1 : 0, "\n";
my $out = Config::config_vars('archname');
print "cv: 1\n";
print "deep_done\n";
