my @a = (5,3,9,1);
my $aref = [10,20,30];
my %h = (k=>'vv', z=>'plain');
my $href = \%h;
my $r = [1,2,3];
my $i = 1; my $key = 'k';
print "var: $$aref[$i] $$href{$key}\n";
print "neg: $$aref[-1]\n";
print "range: @{$r}[1..2]\n";
print "trap1: @{[ sort @a ]}\n";
print "trap2: @{[ map { $_ * 2 } (1..3) ]}\n";
print "trap3: @{[ grep { $_ > 4 } @a ]}\n";
print "trap4: @{[ join(',', @a) ]}\n";
print "side: pre $$aref[0] post\n";
print "adj: $$r[0]$$r[1]\n";
print "mixed: $h{$key} and $$href{$key} and @{[ uc 'ok' ]}\n";
my $s = "x:9";
$s =~ s/^x/$$aref[1]/;
print "subst: $s\n";
my %w = (k => "pct%\nnl");
my $wref = \%w;
print "weird: $$wref{k}\n";
print "deref: @{$r}\n";
print "empty: $$r[99]|\n";
my $sv = 77; my $svref = \$sv;
print "bare: $$svref\n";
print "guards: $h{$key} $aref->[2] @a \$$aref->[1]\n";
my $pid = "$$";
print "pidlen: ", length($pid) > 0 ? 1 : 0, "\n";
my $nested = { a => [ 'q' ] };
print "chain: $$nested{a}[0]\n";
print "end\n";
