my $re1 = qr/x/simx;
print "$re1", "\n";
my $re2 = qr/x/mix;
print "$re2", "\n";
my $re3 = qr/x/n;
print "$re3", "\n";
my $re4 = qr{a.b}i;
print "m4: ", ("AXB" =~ $re4 ? 1 : 0), "\n";
my $re5 = qr(\d+);
print "m5: ", scalar(("x 12 y" =~ $re5) ? 1 : 0), "\n";
my $f = sub { return ref($_[0]); };
print "arg: ", $f->(qr/^x/), "\n";
my $copy = $re5;
print "copy: ", ref($copy), "\n";
my @arr = (qr/^a/);
print "arr: ", ref($arr[0]), "\n";
my $q = "b+";
print "interp-str: ", ("abbbc" =~ /$q/) ? 1 : 0, "\n";
my $qqr = qr/b+/;
print "interp-qr: ", ("abbbc" =~ /$qqr/) ? 1 : 0, "\n";
my $name = "o";
my $w = "foo bar";
$w =~ s/f$name/XX/;
print "subst-str: $w\n";
my $pat = qr/(\w+)/;
my $v = "hey you";
$v =~ s/$pat/X/;
print "subst-qr: $v\n";
my $m = "hi-7";
print "m-list: ", scalar(my @g = ($m =~ $pat)), "\n";
print "deep_done\n";
