use FileHandle;
use IO::Seekable;
use IO::Pipe;
use IO::Socket::UNIX;
use open qw(:std :encoding(UTF-8));
use Fatal qw(open);
print "seek_end=", SEEK_END, "\n";
print "pipe_class=", ref(IO::Pipe->new), "\n";
print "unix_isa=", (IO::Socket::UNIX->isa("IO::Socket") ? 1 : 0), "\n";
my $p = "/tmp/perlc_fh_alias.txt";
my $fh = FileHandle->new($p, "w");
$fh->print("z");
$fh->close;
open my $r, "<", $p;
my $got = <$r>;
close $r;
unlink $p;
print "got=$got";
eval { open my $x, "<", "/no/such/fatal_alias" };
print "fatal=", ($@ =~ /Can't open/ ? 1 : 0), "\n";
print "done\n";
