#!/usr/bin/perl
# Generator for perlc's native Fcntl/POSIX/Errno constant tables.
# Run on the HOST perl; output is committed as src/native_constants.h.
use strict; use warnings;
use IPC::Open3;
sub probe_value {
    my ($expr) = @_;
    my $pid = open3(undef, my $out, my $err = undef, $^X, '-e', $expr);
    my $v = do { local $/; <$out> // '' };
    waitpid $pid, 0;
    chomp $v if defined $v;
    return ($v // '', ($err ? do { local $/; <$err> } // '' : ''));
}
my %tables;
my %tabs;
my %realmod = (fcntl => 'Fcntl', posix => 'POSIX', errno => 'Errno');
my %want = (
    fcntl => [qw(SEEK_SET SEEK_CUR SEEK_END O_CREAT O_EXCL O_TRUNC O_APPEND
                 O_RDONLY O_WRONLY O_RDWR O_NONBLOCK O_BINARY O_TEXT O_NDELAY
                 F_GETFD F_SETFD F_GETFL F_SETFL F_DUPFD F_DUPFD_CLOEXEC
                 F_SETLK F_SETLKW F_GETLK F_RDLCK F_WRLCK F_UNLCK
                 FD_CLOEXEC LOCK_SH LOCK_EX LOCK_UN LOCK_NB
                 S_IRUSR S_IWUSR S_IXUSR S_IRWXU S_IRGRP S_IWGRP S_IXGRP
                 S_IRWXG S_IROTH S_IWOTH S_IXOTH S_IRWXO
                 S_IFMT S_IFDIR S_IFREG S_IFCHR S_IFBLK S_IFIFO S_IFLNK
                 S_IFSOCK IFTODT DT_DIR DT_REG DT_UNKNOWN DT_FIFO DT_SOCK
                 DT_CHR DT_BLK DT_LNK)],
    posix => [qw(LC_ALL LC_COLLATE LC_CTYPE LC_NUMERIC LC_MONETARY
                 LC_MESSAGES S_IRUSR S_IWUSR S_IXUSR S_IRWXU S_IRGRP S_IWGRP
                 S_IXGRP S_IRWXG S_IROTH S_IWOTH S_IXOTH S_IRWXG S_IRWXO
                 S_IFMT S_IFDIR S_IFREG S_IFCHR S_IFBLK S_IFIFO S_IFLNK
                 S_IFSOCK STDOUT_FILENO STDIN_FILENO STDERR_FILENO
                 EXIT_SUCCESS EXIT_FAILURE EINVAL ENOENT EACCES EBADF
                 ENOMEM EEXIST ENOTDIR EISDIR ENOSPC EPERM ESRCH ECHILD
                 EPIPE EINTR EAGAIN EWOULDBLOCK EDEADLK)],
    errno => [qw(ENOENT EBADF EINVAL EACCES EEXIST ENOEXEC EINTR EAGAIN
                 EISDIR ENOTDIR ENOSPC EPERM ESRCH ECHILD EPIPE EROFS
                 ENODEV ENOSYS EIO E2BIG EDOM ERANGE EDEADLK EWOULDBLOCK)],
);
for my $mod (sort keys %want) {
    for my $name (@{$want{$mod}}) {
        my $real = $realmod{$mod};
        my $v = `perl -M$real -e "print $real->$name" 2>/dev/null`;
        next unless defined $v && $v =~ /^-?\d+\s*$/;
        $v =~ s/\s+$//;
        next unless $v =~ /^-?\d+$/;
        next if exists $tabs{$name};
        $tabs{$name} = $v;
    }
}
open my $fh, '>', 'src/native_constants.h' or die $!;
print $fh "/* Generated by tools/gen_native_constants.pl — perlc's native\n";
print $fh " * Fcntl/POSIX/Errno constant values from the host perl. */\n";
print $fh "#ifndef PERLC_NATIVE_CONSTANTS_H\n#define PERLC_NATIVE_CONSTANTS_H\n";
print $fh "static const struct { const char *name; long long value; } perlc_native_consts[] = {\n";
for my $n (sort keys %tabs) {
    print $fh "    { \"$n\", $tabs{$n} },\n";
}
print $fh "};\n";
print $fh "static const int perlc_native_consts_n =\n";
print $fh "    (int)(sizeof(perlc_native_consts) / sizeof(perlc_native_consts[0]));\n";
print $fh "#endif\n";
close $fh;
printf "generated %d constants\n", scalar keys %tabs;
