#!/usr/bin/perl
# Generates src/config_data.h: perlc's native Config module data
# (myconfig() string, config_sh() string, %Config key/value table) from
# the HOST perl. Output is committed so builds don't rerun this.
use strict; use warnings;
my $myconfig = `perl -MConfig -e 'print Config::myconfig()' 2>/dev/null`;
my $configsh = `perl -MConfig -e 'print Config::config_sh()' 2>/dev/null`;
my @keys;
my $keys = `perl -MConfig -e 'print join("\\n", sort keys %Config)' 2>/dev/null`;
for my $k (split /\n/, $keys) { push @keys, $k if defined $k && length $k; }
sub cstr {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/\r/\\r/g;
    $s =~ s/\t/\\t/g;
    $s =~ s/([\x00-\x1f\x7f])/sprintf("\\x%02x", ord($1))/ge;
    return '"' . $s . '"';
}
my @pairs;
for my $k (@keys) {
    my $v = `perl -MConfig -e 'print \$Config{$k} // ""' 2>/dev/null`;
    chomp $v if defined $v;
    push @pairs, [$k, $v // ''];
}
open my $fh, '>', 'src/config_data.h' or die $!;
print $fh "/* Generated by tools/gen_config_data.pl from the host perl. */\n";
print $fh "#ifndef PERLC_CONFIG_DATA_H\n#define PERLC_CONFIG_DATA_H\n";
print $fh "static const char *perlc_config_myconfig =\n", cstr($myconfig), ";\n";
print $fh "static const char *perlc_config_configsh =\n", cstr($configsh), ";\n";
print $fh "static const struct { const char *key; const char *value; } perlc_config_pairs[] = {\n";
for my $p (@pairs) {
    print $fh "    { ", cstr($p->[0]), ", ", cstr($p->[1]), " },\n";
}
print $fh "};\n";
print $fh "static const int perlc_config_pairs_n =\n";
print $fh "    (int)(sizeof(perlc_config_pairs) / sizeof(perlc_config_pairs[0]));\n";
print $fh "#endif\n";
close $fh;
printf "generated: myconfig %d bytes, config_sh %d bytes, %d keys\n",
    length($myconfig), length($configsh), scalar @pairs;
